# Site settings
title:       m20.ca
email:       info@m20.ca
author:      M20
description: "Agence de développement Web"
baseurl:     ""
url:         "http://m20.ca"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-77474366-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username:
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Suivant'
    older: 'Précédent'
  share_buttons:
    text:         'Partager cet article!'
    facebook:     'Partager sur Facebook'
    twitter:      'Partager sur Twitter'
    googleplus:   'Partager sur Google+'
    linkedin:     'Partager sur LinkedIn'
    digg:         'Partager sur Digg'
    tumblr:       'Partager sur Tumblr'
    reddit:       'Partager sur Reddit'
    stumbleupon:  'Partager sur StumbleUpon'
    hackernews:   'Partager sur Hacker News'
  post:
    updated:        'Mis à jour'
    minute_read:    'minutes de lecture'
    related_posts:  'Articles reliés'
  index:
    coming_soon: 'En développement! Revenez nous voir :)'
  contact:
    email:    'Courriel'
    content:  'Votre message'
    subject:  'Nouveau message!'
    submit:   'Envoyer'
    ajax:
      sending:  'envoi en cours..'
      sent:     'Message envoyé!'
      error:    'Erreur!'
  thanks: 'Merci de nous avoir contacté! Nous vous répondrons dans les plus brefs délais!'
  og_locale: 'fr_CA'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
